CREATE DATABASE IF NOT EXISTS campusdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE campusdb;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  registro VARCHAR(32) NOT NULL UNIQUE,
  nombres  VARCHAR(120) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  email    VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
